In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\shrut\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\shrut\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shrut\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shrut\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shrut\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\shrut\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [4]:
## Load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
##Preprocess the data
##drop irrelevant featrues

data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
##encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
##Onehot enocde geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder(sparse_output=False)
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [8]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
##Combine one hot encoded cols with original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [12]:
##save the encoders and scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [21]:
##Divide dataset into independent and dependent features X =independent, Y=dependent

X=data.drop('Exited',axis=1)
Y=data['Exited']

##Split data in traing and testing set

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)


##Scale these features

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [23]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [25]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [33]:
!pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.18.0-cp312-cp312-win_amd64.whl.metadata (3.3 kB)
Collecting tensorflow-intel==2.18.0 (from tensorflow)
  Downloading tensorflow_intel-2.18.0-cp312-cp312-win_amd64.whl.metadata (4.9 kB)
Collecting absl-py>=1.0.0 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
Collecting google-pasta>=0.1.1 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\shrut\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in c:\users\shrut\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (4.25.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\shrut\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\shrut\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (75.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\shrut\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.16.0)
Collecting termcolor>=1.1.0 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading termcolor-2.5.0-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\shrut\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (4.11.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\shrut\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.14.1)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading grpcio-1.70.0-cp312-cp312-win_amd64.whl.metadata (4.0 kB)
Collecting tensorboard<2.19,>=2.18 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Collecting keras>=3.5.0 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading keras-3.8.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in c:\users\shrut\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in c:\users\shrut\anaconda3\lib\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.11.0)
Collecting ml-dtypes<0.5.0,>=0.4.0 (from tensorflow-intel==2.18.0->tensorflow)
  Downloading ml_dtypes-0.4.1-cp312-cp312-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\shrut\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.18.0->tensorflow) (0.44.0)
Requirement already satisfied: rich in c:\users\shrut\anaconda3\lib\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (13.7.1)
Collecting namex (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow)
  Downloading namex-0.0.8-py3-none-any.whl.metadata (246 bytes)
Collecting optree (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow)
  Downloading optree-0.14.0-cp312-cp312-win_amd64.whl.metadata (48 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\shrut\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shrut\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shrut\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shrut\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.18.0->tensorflow) (2024.12.14)
Requirement already satisfied: markdown>=2.6.8 in c:\users\shrut\anaconda3\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.4.1)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow)
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\shrut\anaconda3\lib\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\shrut\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (2.1.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\shrut\anaconda3\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\shrut\anaconda3\lib\site-packages (from rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\shrut\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.1.0)
Downloading tensorflow-2.18.0-cp312-cp312-win_amd64.whl (7.5 kB)
Downloading tensorflow_intel-2.18.0-cp312-cp312-win_amd64.whl (390.3 MB)
   ---------------------------------------- 0.0/390.3 MB ? eta -:--:--
   ---------------------------------------- 3.4/390.3 MB 18.3 MB/s eta 0:00:22
    --------------------------------------- 6.6/390.3 MB 16.1 MB/s eta 0:00:24
   - -------------------------------------- 10.7/390.3 MB 17.2 MB/s eta 0:00:23
   - -------------------------------------- 11.5/390.3 MB 14.7 MB/s eta 0:00:26
   - -------------------------------------- 12.6/390.3 MB 12.3 MB/s eta 0:00:31
   - -------------------------------------- 13.9/390.3 MB 11.0 MB/s eta 0:00:35
   - -------------------------------------- 16.0/390.3 MB 10.9 MB/s eta 0:00:35
   - -------------------------------------- 18.1/390.3 MB 10.9 MB/s eta 0:00:35
   -- ------------------------------------- 20.4/390.3 MB 10.9 MB/s eta 0:00:34
   -- ------------------------------------- 22.8/390.3 MB 11.0 MB/s eta 0:00:34
   -- ------------------------------------- 23.9/390.3 MB 10.5 MB/s eta 0:00:35
   -- ------------------------------------- 24.9/390.3 MB 10.1 MB/s eta 0:00:37
   -- ------------------------------------- 27.0/390.3 MB 10.1 MB/s eta 0:00:37
   --- ------------------------------------ 29.4/390.3 MB 10.1 MB/s eta 0:00:36
   --- ------------------------------------ 31.7/390.3 MB 10.1 MB/s eta 0:00:36
   --- ------------------------------------ 33.3/390.3 MB 10.0 MB/s eta 0:00:36
   --- ------------------------------------ 35.4/390.3 MB 9.9 MB/s eta 0:00:36
   --- ------------------------------------ 37.7/390.3 MB 10.0 MB/s eta 0:00:36
   ---- ----------------------------------- 40.1/390.3 MB 10.1 MB/s eta 0:00:35
   ---- ----------------------------------- 41.4/390.3 MB 9.9 MB/s eta 0:00:36
   ---- ----------------------------------- 42.5/390.3 MB 9.6 MB/s eta 0:00:37
   ---- ----------------------------------- 44.6/390.3 MB 9.6 MB/s eta 0:00:36
   ---- ----------------------------------- 47.2/390.3 MB 9.7 MB/s eta 0:00:36
   ---- ----------------------------------- 48.8/390.3 MB 9.6 MB/s eta 0:00:36
   ----- ---------------------------------- 50.6/390.3 MB 9.6 MB/s eta 0:00:36
   ----- ---------------------------------- 53.0/390.3 MB 9.6 MB/s eta 0:00:36
   ----- ---------------------------------- 55.1/390.3 MB 9.6 MB/s eta 0:00:35
   ----- ---------------------------------- 57.1/390.3 MB 9.7 MB/s eta 0:00:35
   ------ --------------------------------- 59.0/390.3 MB 9.6 MB/s eta 0:00:35
   ------ --------------------------------- 60.6/390.3 MB 9.6 MB/s eta 0:00:35
   ------ --------------------------------- 62.4/390.3 MB 9.5 MB/s eta 0:00:35
   ------ --------------------------------- 64.5/390.3 MB 9.5 MB/s eta 0:00:35
   ------ --------------------------------- 67.4/390.3 MB 9.6 MB/s eta 0:00:34
   ------- -------------------------------- 69.5/390.3 MB 9.6 MB/s eta 0:00:34
   ------- -------------------------------- 70.8/390.3 MB 9.5 MB/s eta 0:00:34
   ------- -------------------------------- 72.4/390.3 MB 9.4 MB/s eta 0:00:34
   ------- -------------------------------- 73.9/390.3 MB 9.4 MB/s eta 0:00:34
   ------- -------------------------------- 76.5/390.3 MB 9.4 MB/s eta 0:00:34
   -------- ------------------------------- 78.6/390.3 MB 9.5 MB/s eta 0:00:33
   -------- ------------------------------- 80.5/390.3 MB 9.4 MB/s eta 0:00:33
   -------- ------------------------------- 81.0/390.3 MB 9.3 MB/s eta 0:00:34
   -------- ------------------------------- 83.6/390.3 MB 9.3 MB/s eta 0:00:33
   -------- ------------------------------- 86.8/390.3 MB 9.4 MB/s eta 0:00:33
   --------- ------------------------------ 89.4/390.3 MB 9.5 MB/s eta 0:00:32
   --------- ------------------------------ 91.2/390.3 MB 9.5 MB/s eta 0:00:32
   --------- ------------------------------ 93.1/390.3 MB 9.5 MB/s eta 0:00:32
   --------- ------------------------------ 94.1/390.3 MB 9.4 MB/s eta 0:00:32
   --------- ------------------------------ 95.4/390.3 MB 9.4 MB/s eta 0:00:32
   ---------- ----------------------------- 98.0/390.3 MB 9.4 MB/s eta 0:00:32
   ---------- ----------------------------- 99.6/390.3 MB 9.3 MB/s eta 0:00:32
   ---------- ----------------------------- 101.7/390.3 MB 9.3 MB/s eta 0:00:31
   ---------- ----------------------------- 104.3/390.3 MB 9.4 MB/s eta 0:00:31
   ---------- ----------------------------- 106.7/390.3 MB 9.4 MB/s eta 0:00:31
   ----------- ---------------------------- 108.5/390.3 MB 9.4 MB/s eta 0:00:30
   ----------- ---------------------------- 110.4/390.3 MB 9.4 MB/s eta 0:00:30
   ----------- ---------------------------- 112.2/390.3 MB 9.4 MB/s eta 0:00:30
   ----------- ---------------------------- 113.8/390.3 MB 9.3 MB/s eta 0:00:30
   ----------- ---------------------------- 115.6/390.3 MB 9.3 MB/s eta 0:00:30
   ------------ --------------------------- 117.4/390.3 MB 9.3 MB/s eta 0:00:30
   ------------ --------------------------- 119.8/390.3 MB 9.3 MB/s eta 0:00:29
   ------------ --------------------------- 121.9/390.3 MB 9.3 MB/s eta 0:00:29
   ------------ --------------------------- 123.7/390.3 MB 9.3 MB/s eta 0:00:29
   ------------ --------------------------- 125.6/390.3 MB 9.3 MB/s eta 0:00:29
   ------------ --------------------------- 126.6/390.3 MB 9.3 MB/s eta 0:00:29
   ------------- -------------------------- 129.5/390.3 MB 9.3 MB/s eta 0:00:28
   ------------- -------------------------- 132.1/390.3 MB 9.4 MB/s eta 0:00:28
   ------------- -------------------------- 133.4/390.3 MB 9.3 MB/s eta 0:00:28
   ------------- -------------------------- 134.7/390.3 MB 9.3 MB/s eta 0:00:28
   ------------- -------------------------- 136.6/390.3 MB 9.3 MB/s eta 0:00:28
   -------------- ------------------------- 138.9/390.3 MB 9.3 MB/s eta 0:00:28
   -------------- ------------------------- 141.3/390.3 MB 9.3 MB/s eta 0:00:27
   -------------- ------------------------- 143.7/390.3 MB 9.3 MB/s eta 0:00:27
   -------------- ------------------------- 145.0/390.3 MB 9.3 MB/s eta 0:00:27
   --------------- ------------------------ 147.1/390.3 MB 9.3 MB/s eta 0:00:27
   --------------- ------------------------ 148.4/390.3 MB 9.3 MB/s eta 0:00:27
   --------------- ------------------------ 150.2/390.3 MB 9.3 MB/s eta 0:00:26
   --------------- ------------------------ 152.6/390.3 MB 9.3 MB/s eta 0:00:26
   --------------- ------------------------ 154.4/390.3 MB 9.3 MB/s eta 0:00:26
   ---------------- ----------------------- 156.5/390.3 MB 9.3 MB/s eta 0:00:26
   ---------------- ----------------------- 158.6/390.3 MB 9.3 MB/s eta 0:00:25
   ---------------- ----------------------- 160.2/390.3 MB 9.3 MB/s eta 0:00:25
   ---------------- ----------------------- 162.3/390.3 MB 9.3 MB/s eta 0:00:25
   ---------------- ----------------------- 163.8/390.3 MB 9.3 MB/s eta 0:00:25
   ----------------- ---------------------- 166.5/390.3 MB 9.3 MB/s eta 0:00:25
   ----------------- ---------------------- 168.3/390.3 MB 9.3 MB/s eta 0:00:24
   ----------------- ---------------------- 170.4/390.3 MB 9.3 MB/s eta 0:00:24
   ----------------- ---------------------- 171.2/390.3 MB 9.3 MB/s eta 0:00:24
   ----------------- ---------------------- 172.8/390.3 MB 9.2 MB/s eta 0:00:24
   ----------------- ---------------------- 174.9/390.3 MB 9.2 MB/s eta 0:00:24
   ------------------ --------------------- 177.5/390.3 MB 9.3 MB/s eta 0:00:23
   ------------------ --------------------- 179.8/390.3 MB 9.3 MB/s eta 0:00:23
   ------------------ --------------------- 180.9/390.3 MB 9.2 MB/s eta 0:00:23
   ------------------ --------------------- 182.2/390.3 MB 9.2 MB/s eta 0:00:23
   ------------------ --------------------- 184.8/390.3 MB 9.2 MB/s eta 0:00:23
   ------------------- -------------------- 187.7/390.3 MB 9.3 MB/s eta 0:00:22
   ------------------- -------------------- 189.3/390.3 MB 9.3 MB/s eta 0:00:22
   ------------------- -------------------- 190.6/390.3 MB 9.2 MB/s eta 0:00:22
   ------------------- -------------------- 192.9/390.3 MB 9.2 MB/s eta 0:00:22
   -------------------- ------------------- 196.1/390.3 MB 9.3 MB/s eta 0:00:21
   -------------------- ------------------- 198.4/390.3 MB 9.3 MB/s eta 0:00:21
   -------------------- ------------------- 200.0/390.3 MB 9.3 MB/s eta 0:00:21
   -------------------- ------------------- 201.1/390.3 MB 9.2 MB/s eta 0:00:21
   -------------------- ------------------- 202.9/390.3 MB 9.2 MB/s eta 0:00:21
   -------------------- ------------------- 204.5/390.3 MB 9.2 MB/s eta 0:00:21
   --------------------- ------------------ 206.0/390.3 MB 9.2 MB/s eta 0:00:21
   --------------------- ------------------ 208.9/390.3 MB 9.2 MB/s eta 0:00:20
   --------------------- ------------------ 210.5/390.3 MB 9.2 MB/s eta 0:00:20
   --------------------- ------------------ 213.1/390.3 MB 9.3 MB/s eta 0:00:20
   ---------------------- ----------------- 214.7/390.3 MB 9.2 MB/s eta 0:00:19
   ---------------------- ----------------- 216.3/390.3 MB 9.2 MB/s eta 0:00:19
   ---------------------- ----------------- 218.1/390.3 MB 9.2 MB/s eta 0:00:19
   ---------------------- ----------------- 219.7/390.3 MB 9.2 MB/s eta 0:00:19
   ---------------------- ----------------- 222.0/390.3 MB 9.2 MB/s eta 0:00:19
   ---------------------- ----------------- 224.4/390.3 MB 9.2 MB/s eta 0:00:18
   ----------------------- ---------------- 226.8/390.3 MB 9.3 MB/s eta 0:00:18
   ----------------------- ---------------- 228.3/390.3 MB 9.2 MB/s eta 0:00:18
   ----------------------- ---------------- 229.9/390.3 MB 9.2 MB/s eta 0:00:18
   ----------------------- ---------------- 231.5/390.3 MB 9.2 MB/s eta 0:00:18
   ----------------------- ---------------- 233.3/390.3 MB 9.2 MB/s eta 0:00:18
   ------------------------ --------------- 235.9/390.3 MB 9.2 MB/s eta 0:00:17
   ------------------------ --------------- 237.0/390.3 MB 9.2 MB/s eta 0:00:17
   ------------------------ --------------- 237.0/390.3 MB 9.2 MB/s eta 0:00:17
   ------------------------ --------------- 237.8/390.3 MB 9.1 MB/s eta 0:00:17
   ------------------------ --------------- 240.4/390.3 MB 9.1 MB/s eta 0:00:17
   ------------------------- -------------- 244.1/390.3 MB 9.2 MB/s eta 0:00:16
   ------------------------- -------------- 246.9/390.3 MB 9.2 MB/s eta 0:00:16
   ------------------------- -------------- 248.5/390.3 MB 9.2 MB/s eta 0:00:16
   ------------------------- -------------- 250.9/390.3 MB 9.2 MB/s eta 0:00:16
   ------------------------- -------------- 253.0/390.3 MB 9.2 MB/s eta 0:00:15
   -------------------------- ------------- 254.3/390.3 MB 9.2 MB/s eta 0:00:15
   -------------------------- ------------- 256.4/390.3 MB 9.2 MB/s eta 0:00:15
   -------------------------- ------------- 258.2/390.3 MB 9.2 MB/s eta 0:00:15
   -------------------------- ------------- 260.3/390.3 MB 9.2 MB/s eta 0:00:15
   -------------------------- ------------- 261.9/390.3 MB 9.2 MB/s eta 0:00:15
   --------------------------- ------------ 263.5/390.3 MB 9.1 MB/s eta 0:00:14
   --------------------------- ------------ 265.8/390.3 MB 9.1 MB/s eta 0:00:14
   --------------------------- ------------ 267.6/390.3 MB 9.1 MB/s eta 0:00:14
   --------------------------- ------------ 269.5/390.3 MB 9.0 MB/s eta 0:00:14
   --------------------------- ------------ 271.8/390.3 MB 9.0 MB/s eta 0:00:14
   ---------------------------- ----------- 273.9/390.3 MB 9.0 MB/s eta 0:00:13
   ---------------------------- ----------- 275.5/390.3 MB 9.1 MB/s eta 0:00:13
   ---------------------------- ----------- 277.3/390.3 MB 9.1 MB/s eta 0:00:13
   ---------------------------- ----------- 279.4/390.3 MB 9.1 MB/s eta 0:00:13
   ---------------------------- ----------- 280.8/390.3 MB 9.0 MB/s eta 0:00:13
   ---------------------------- ----------- 282.6/390.3 MB 9.0 MB/s eta 0:00:12
   ----------------------------- ---------- 285.5/390.3 MB 9.0 MB/s eta 0:00:12
   ----------------------------- ---------- 288.4/390.3 MB 9.1 MB/s eta 0:00:12
   ----------------------------- ---------- 289.7/390.3 MB 9.1 MB/s eta 0:00:12
   ----------------------------- ---------- 291.5/390.3 MB 9.1 MB/s eta 0:00:11
   ------------------------------ --------- 293.3/390.3 MB 9.0 MB/s eta 0:00:11
   ------------------------------ --------- 295.7/390.3 MB 9.1 MB/s eta 0:00:11
   ------------------------------ --------- 297.5/390.3 MB 9.1 MB/s eta 0:00:11
   ------------------------------ --------- 299.4/390.3 MB 9.1 MB/s eta 0:00:11
   ------------------------------ --------- 301.5/390.3 MB 9.0 MB/s eta 0:00:10
   ------------------------------- -------- 302.8/390.3 MB 9.0 MB/s eta 0:00:10
   ------------------------------- -------- 304.3/390.3 MB 9.1 MB/s eta 0:00:10
   ------------------------------- -------- 306.7/390.3 MB 9.1 MB/s eta 0:00:10
   ------------------------------- -------- 309.1/390.3 MB 9.1 MB/s eta 0:00:09
   ------------------------------- -------- 310.1/390.3 MB 9.0 MB/s eta 0:00:09
   ------------------------------- -------- 311.7/390.3 MB 9.0 MB/s eta 0:00:09
   -------------------------------- ------- 313.3/390.3 MB 9.0 MB/s eta 0:00:09
   -------------------------------- ------- 315.4/390.3 MB 9.0 MB/s eta 0:00:09
   -------------------------------- ------- 318.5/390.3 MB 9.1 MB/s eta 0:00:08
   -------------------------------- ------- 321.1/390.3 MB 9.1 MB/s eta 0:00:08
   --------------------------------- ------ 322.2/390.3 MB 9.0 MB/s eta 0:00:08
   --------------------------------- ------ 323.7/390.3 MB 9.0 MB/s eta 0:00:08
   --------------------------------- ------ 326.1/390.3 MB 9.1 MB/s eta 0:00:08
   --------------------------------- ------ 328.7/390.3 MB 9.1 MB/s eta 0:00:07
   --------------------------------- ------ 331.1/390.3 MB 9.1 MB/s eta 0:00:07
   ---------------------------------- ----- 332.7/390.3 MB 9.1 MB/s eta 0:00:07
   ---------------------------------- ----- 334.2/390.3 MB 9.1 MB/s eta 0:00:07
   ---------------------------------- ----- 336.3/390.3 MB 9.1 MB/s eta 0:00:06
   ---------------------------------- ----- 338.4/390.3 MB 9.1 MB/s eta 0:00:06
   ---------------------------------- ----- 340.8/390.3 MB 9.1 MB/s eta 0:00:06

In [37]:
import tensorflow as tf
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard 
import datetime

In [53]:
##Build ANN model
##1 HL connected with input layer
model=Sequential ([
    Input(shape=(X_train.shape[1],)),
    Dense(64,activation='relu'),
    # input_shape=(X_train.shape[1],)
    Dense(32,activation='relu'),
    ##2 HL
    Dense(1,activation='sigmoid')
    ##output layer
])

In [55]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [75]:
#compile the code import tensorflow
import tensorflow as tf
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=opt,loss="binary_crossentropy", metrics=['accuracy'])
## Set up the tensorboard from tensorflow.keras.callbacks
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard 
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d -%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

##Set up earlystopping... 
early_stopping_callback=EarlyStopping(monitor='val_loss', patience=5,restore_best_weights=True)

In [81]:
##train the model
history=model.fit(
    X_train, Y_train,validation_data=(X_test,Y_test),epochs=100,callbacks=[tensorflow_callback, early_stopping_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8052 - loss: 0.4447 - val_accuracy: 0.8595 - val_loss: 0.3561
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8557 - loss: 0.3555 - val_accuracy: 0.8625 - val_loss: 0.3540
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8553 - loss: 0.3490 - val_accuracy: 0.8595 - val_loss: 0.3414
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8665 - loss: 0.3335 - val_accuracy: 0.8610 - val_loss: 0.3500
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8642 - loss: 0.3304 - val_accuracy: 0.8655 - val_loss: 0.3410
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8646 - loss: 0.3255 - val_accuracy: 0.8555 - val_loss: 0.3525
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8602 - loss: 0.3378 - val_accuracy: 0.8555 - val_loss: 0.3586
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8617 - loss: 0.3343 - val_accuracy: 0.8615 - val_loss: 0.3518
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8644 - loss: 0.3371 - val_accuracy: 0.8580 - val_loss: 0.3603
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8661 - loss: 0.3292 - val_accuracy: 0.8630 - val_loss: 0.3428

In [85]:
model.save('model.h5')
# model.save ('model.keras")
# load Tensorboard extension
%load_ext tensorboard
%tensorboard --logdir logs/fit

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [89]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [91]:
### Load the trained model, scaler pickle,onehot
model=load_model('model.h5')

## load the encoder and scaler
with open('onehot_encoder_geo.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)

with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [93]:
input_data={'CreditScore': 600,
'Geography':  'France',
'Gender':  'Male',
'Age': 40,
'Tenure':  3,
'Balance':  60000, 
'NumOfProducts':  2,
'HasCrCard':  1,
'IsActiveMember':  1,
'EstimatedSalary':  50000}

In [110]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [112]:
## Encode categorical variables
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [142]:

geo_encoded = label_encoder_geo.transform([[input_data['Geography']]])
geo_encoded_df = pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df
## concatination one hot encoded 
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

C:\Users\shrut\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [144]:
## Scaling the input data
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [146]:
## PRedict churn
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

array([[0.05751377]], dtype=float32)

In [148]:
prediction_proba = prediction[0][0]

In [150]:
prediction_proba

0.057513773

In [152]:
if prediction_proba > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.